### ISSUE TITLE
Building with latest Flutter 1.27.0-4.0.pre • channel dev 

### ISSUE THREAD

**Issue by mbasa-georepublic** [moovida/smash#103]
Building `master` with the latest dev version produces this error during `pub get`: 

```
Because smash depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because smash depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because smash depends on intl ^0.16.1, version solving failed.)
```

upgrading to 0.17.0 in the pubspec.yaml will produce this error on `pub get`:

```
Because dart_jts >=0.0.5 depends on intl ^0.16.1 and smash depends on intl ^0.17.0, dart_jts >=0.0.5 is forbidden.
So, because smash depends on dart_jts ^0.0.6, version solving failed.
pub get failed (1; So, because smash depends on dart_jts ^0.0.6, version solving failed.)
```

**Comment by moovida** [comment]
Hi @mbasa-georepublic , since the latest changes in the dev channel and with the introduction of nullsafety there is a huge caos in the dependency tree, with many packages not having upgraded and supplying an intermediate version. After some tests I decided it would be safer to move on the stable channel and fix the few issue that where left. So please switch to flutter stable. The only bad thing with this is that we loose temporarily desktop support with is incredibly useful while developing :-(

**Comment by mbasa-georepublic** [comment]
It will be nice if we can use **flutter 2.0** already. I am still having problems compiling the master branch with the new version.

**Comment by moovida** [comment]
At the moment the plugins ecosystem is going through a dependency hell due to the null safety thing.

I am right now trying to compile SMASH with the new stable flutter 2.0.1, but am having issues with the extended_image package. Did you already get further than that?

**Comment by moovida** [comment]
@mbasa-georepublic The current master branch now works with flutter 2.0.1.

**Comment by mbasa-georepublic** [comment]
Great news @moovida . Thanks.

**Comment by FloDoc** [comment]
This is great! I just showed up today to see if this was working! Tested and working! Thanks for all your hard work!
